function modelName = build_quarter_car_simulink(overwriteExisting)
% Generate an editable AFC quarter-car Simulink block diagram.
if nargin < 1
    overwriteExisting = false;
end
cfg = quarter_car_replication_config();
modelName = 'QuarterCar_AFC_Replication';
modelFile = [modelName, '.slx'];

if exist(modelFile, 'file')
    if ~overwriteExisting
        error('File exists: %s. Pass true only if you want to rebuild it.', modelFile);
    end
    if bdIsLoaded(modelName)
        if strcmp(get_param(modelName, 'Dirty'), 'on')
            error('The loaded model has unsaved edits; save or close it before rebuilding.');
        end
        close_system(modelName, 0);
    end
    delete(modelFile);
end

new_system(modelName);
cleanupModel = onCleanup(@() close_system(modelName, 0));
set_param(modelName, 'StopTime', num2str(cfg.sim.duration_s), ...
    'Solver', 'ode4', 'FixedStep', '0.001', ...
    'SaveTime', 'on', 'TimeSaveName', 'tout');

add_block('simulink/Sources/Clock', [modelName, '/Clock'], ...
    'Position', [35 105 65 135]);
add_block('simulink/Signal Routing/Goto', [modelName, '/Time tag'], ...
    'GotoTag', 'model_time', 'TagVisibility', 'global', ...
    'Position', [105 110 165 130]);
add_block('simulink/Signal Routing/From', [modelName, '/Controller time'], ...
    'GotoTag', 'model_time', 'Position', [155 130 205 150]);
add_block('simulink/Signal Routing/From', [modelName, '/Controller state'], ...
    'GotoTag', 'model_state', 'Position', [155 170 205 190]);
add_block('simulink/User-Defined Functions/MATLAB Function', ...
    [modelName, '/AFC Controller'], 'Position', [255 110 440 210]);
add_block('simulink/Discrete/Zero-Order Hold', [modelName, '/50 Hz ZOH'], ...
    'SampleTime', num2str(cfg.sim.sample_time_s), ...
    'Position', [510 140 550 180]);
add_block('simulink/Signal Routing/Goto', [modelName, '/Control tag'], ...
    'GotoTag', 'model_control', 'TagVisibility', 'global', ...
    'Position', [620 145 690 165]);
add_block('simulink/Signal Routing/From', [modelName, '/Plant state'], ...
    'GotoTag', 'model_state', 'Position', [185 390 245 410]);
add_block('simulink/Signal Routing/From', [modelName, '/Plant control'], ...
    'GotoTag', 'model_control', 'Position', [185 445 245 465]);
add_block('simulink/User-Defined Functions/MATLAB Function', ...
    [modelName, '/Quarter-car plant'], 'Position', [330 350 555 550]);
add_block('simulink/Continuous/Integrator', [modelName, '/Quarter-car states'], ...
    'InitialCondition', 'zeros(5,1)', 'Position', [645 390 685 430]);
add_block('simulink/Signal Routing/Goto', [modelName, '/State tag'], ...
    'GotoTag', 'model_state', 'TagVisibility', 'global', ...
    'Position', [755 395 825 415]);
add_block('simulink/Sources/Sine Wave', [modelName, '/Road input'], ...
    'Amplitude', '0.043', 'Frequency', num2str(2*pi*0.505, 16), ...
    'Phase', '0', 'Bias', '0', 'SampleTime', '0', ...
    'Position', [155 495 225 525]);

add_workspace_sink(modelName, 'State log', 'x_states', [755 450 860 475]);
add_workspace_sink(modelName, 'Road log', 'road', [155 570 260 595]);
add_workspace_sink(modelName, 'Control log', 'control', [620 215 725 240]);
add_workspace_sink(modelName, 'Acceleration log', 'acceleration', ...
    [645 490 750 515]);

controllerBlock = [modelName, '/AFC Controller'];
controllerChart = find(sfroot, '-isa', 'Stateflow.EMChart', ...
    'Path', controllerBlock);
controllerChart.Script = controller_code(cfg);
plantBlock = [modelName, '/Quarter-car plant'];
plantChart = find(sfroot, '-isa', 'Stateflow.EMChart', 'Path', plantBlock);
plantChart.Script = plant_code(cfg);

add_line(modelName, 'Clock/1', 'Time tag/1', 'autorouting', 'on');
add_line(modelName, 'Controller time/1', 'AFC Controller/1', ...
    'autorouting', 'on');
add_line(modelName, 'Controller state/1', 'AFC Controller/2', ...
    'autorouting', 'on');
add_line(modelName, 'AFC Controller/1', '50 Hz ZOH/1', 'autorouting', 'on');
add_line(modelName, '50 Hz ZOH/1', 'Control tag/1', 'autorouting', 'on');
add_line(modelName, '50 Hz ZOH/1', 'Control log/1', 'autorouting', 'on');
add_line(modelName, 'Plant state/1', 'Quarter-car plant/1', ...
    'autorouting', 'on');
add_line(modelName, 'Plant control/1', 'Quarter-car plant/2', ...
    'autorouting', 'on');
add_line(modelName, 'Road input/1', 'Quarter-car plant/3', 'autorouting', 'on');
add_line(modelName, 'Road input/1', 'Road log/1', 'autorouting', 'on');
add_line(modelName, 'Quarter-car plant/1', 'Quarter-car states/1', ...
    'autorouting', 'on');
add_line(modelName, 'Quarter-car plant/2', 'Acceleration log/1', ...
    'autorouting', 'on');
add_line(modelName, 'Quarter-car states/1', 'State tag/1', ...
    'autorouting', 'on');
add_line(modelName, 'Quarter-car states/1', 'State log/1', ...
    'autorouting', 'on');
set_param(modelName, 'SimulationCommand', 'update');
save_system(modelName, modelFile);
clear cleanupModel;
open_system(modelName);
end

function add_workspace_sink(modelName, blockName, variableName, position)
path = [modelName, '/', blockName];
add_block('simulink/Sinks/To Workspace', path, ...
    'VariableName', variableName, 'SaveFormat', 'Timeseries', ...
    'Position', position);
end

function code = controller_code(cfg)
code = sprintf([ ...
    'function u = fcn(t,x)\n' ...
    'delta = %.16g; deltaBar = %.16g;\n' ...
    'mu1 = (%.16g-%.16g)*exp(-%.16g*t)+%.16g;\n' ...
    'mu2 = (%.16g-%.16g)*exp(-%.16g*t)+%.16g;\n' ...
    'mu3 = (%.16g-%.16g)*exp(-%.16g*t)+%.16g;\n' ...
    'z1 = min(max(x(1)/mu1,-delta+1e-8),deltaBar-1e-8);\n' ...
    'e1 = 0.5*log((delta+z1)/(deltaBar-z1));\n' ...
    'u1 = -%.16g*e1;\n' ...
    'z2 = min(max((x(2)-u1)/mu2,-delta+1e-8),deltaBar-1e-8);\n' ...
    'e2 = 0.5*log((delta+z2)/(deltaBar-z2));\n' ...
    'u2 = -%.16g*e2;\n' ...
    'z3 = min(max((x(5)-u2)/mu3,-delta+1e-8),deltaBar-1e-8);\n' ...
    'e3 = 0.5*log((delta+z3)/(deltaBar-z3));\n' ...
    'u = min(max(-%.16g*e3,-%.16g),%.16g);\n' ...
    'end\n'], ...
    cfg.afc.delta, cfg.afc.delta_bar, ...
    cfg.afc.mu0(1), cfg.afc.mu_inf(1), cfg.afc.alpha(1), cfg.afc.mu_inf(1), ...
    cfg.afc.mu0(2), cfg.afc.mu_inf(2), cfg.afc.alpha(2), cfg.afc.mu_inf(2), ...
    cfg.afc.mu0(3), cfg.afc.mu_inf(3), cfg.afc.alpha(3), cfg.afc.mu_inf(3), ...
    cfg.afc.k(1), cfg.afc.k(2), cfg.afc.k(3), ...
    cfg.sim.voltage_limit_V, cfg.sim.voltage_limit_V);
end

function code = plant_code(cfg)
p = cfg.plant;
a = cfg.actuator;
code = sprintf([ ...
    'function [dx,acc] = fcn(x,u,zr)\n' ...
    'ms=%.16g; mu=%.16g; ks=%.16g; ksn=%.16g; bs=%.16g;\n' ...
    'kt=%.16g; bt=%.16g; area=%.16g; kappa=%.16g;\n' ...
    'beta=%.16g; cRel=%.16g; bu=%.16g; pressureLimit=%.16g;\n' ...
    'd=x(1)-x(3); v=x(2)-x(4);\n' ...
    'Fs=ks*d+ksn*d^3; Fd=bs*v;\n' ...
    'Ft=kt*(x(3)-zr); Fb=bt*x(4);\n' ...
    'F=area*x(5)/kappa;\n' ...
    'acc=(-Fd-Fs+F)/ms;\n' ...
    'dx=zeros(5,1); dx(1)=x(2); dx(2)=acc; dx(3)=x(4);\n' ...
    'dx(4)=(Fd+Fs-Ft-Fb-F)/mu;\n' ...
    'dx(5)=-beta*x(5)-cRel*v+bu*u;\n' ...
    'if x(5)>=kappa*pressureLimit && dx(5)>0, dx(5)=0; end\n' ...
    'if x(5)<=-kappa*pressureLimit && dx(5)<0, dx(5)=0; end\n' ...
    'end\n'], p.ms_kg, p.mu_kg, p.ks_N_m, p.ksn_N_m3, ...
    p.bs_Ns_m, p.kt_N_m, p.bt_Ns_m, p.area_m2, p.kappa, ...
    a.beta_per_s, a.cRel, a.bu_per_s_V, a.pressure_limit_Pa);
end
